<?php if (is_page('virginia-fuel-prices') || in_category(array('va-to-nc-line','va-to-nc-line-cruising-news','fuel-prices-va-to-nc-line','bridges-va-to-nc-line'))) { ?>
<?php echo adrotate_banner(3,0,8,8); ?>
<?php echo adrotate_banner(4,0,8,8); ?>
<?php } elseif (is_page('north-carolina-fuel-prices') || in_category(array('1-northern-mouth-of-alligator-river','intersection-of-aicw-and-bogue-inlet','intersection-of-aicw-and-browns-inlet','intersection-of-aicw-new-river-and-new-river-inlet','intersection-of-aicw-and-carolina-beach-inlet','2-intersection-of-aicw-and-lockwoods-folly-inlet','3-intersection-of-icw-and-shallotte-inlet','nc-north-carolina','nc-dismal-swamp-rotue','nc-virginia-cut','nc-albemarle-sound','nc-crotoan-roanoke-pamlico-sound','nc-alligator-river-pungo-river','nc-pamlico-river','nc-goose-creek-bay-river','nc-neuse-river','nc-adams-creek-beaufort-morehead-city','nc-bogue-sound-new-river','nc-swan-point-snows-cut','nc-cape-fear-river','nc-southport-calabash','anchorages-north-carolina','anchorages-icw-dismal-swamp-route','anchorages-icw-nc-virginia-cut-route','anchorages-pamlico-crotoan-roanoke-sound','anchorages-icw-alligator-river-pungo-river','anchorages-pamlico-river','anchorages-icw-goose-creek-bay-river','anchorages-neuse-river','anchorages-icw-adams-creek-beaufort-morehead-city','anchorages-icw-bogue-sound-new-river','anchorages-icw-swan-point-snows-cut','anchorages-cape-fear-river','anchorages-icw-southport-calabash','nc-marinas','marinas-nc-dismal-swamp-rotue','marinas-nc-virginia-cut','marinas-nc-crotoan-roanoke-pamlico-sound','marinas-nc-alligator-river-pungo-river','marinas-nc-pamlico-river','marinas-nc-goose-creek-bay-river','marinas-nc-neuse-river','marinas-nc-adams-creek-beaufort-morehead-city','marinas-nc-bogue-sound-new-river','marinas-nc-swan-point-snows-cut','marinas-nc-cape-fear-river','marinas-nc-southport-calabash','nc-fuel-prices','bridges-north-carolina','marinas-nc-albemarle-sound','nc-chart-view-alerts','nc-aicw-problems','north-carolina-lpg-cng-availability','ln™-nc-news','north-carolina-marina-master-index','beaufort-nc-photo-gallery'))) { ?>
<?php echo adrotate_banner(5,0,8,8); ?>
<?php echo adrotate_banner(6,0,8,8); ?>
<?php } elseif (is_page('south-carolina-fuel-prices') || in_category(array('south-carolina','sc-south-carolina','sc-calabash-socastee-bridge','sc-waccamaw-river-winyah-bay','sc-georgetown-winyah-peedee-black-river','sc-belle-isle-sullivans-island','sc-charleston-cooper-wando-ashley','sc-stono-north-edisto','sc-dawho-ashepoo-coosaw-cutoff','sc-coosaw-ladys-island-bridge','sc-beaufort','sc-beaufort-calibogue-hilton-head','sc-cooper-savannah','anchorages-south-carolina','anchorages-icw-calabash-socastee-bridge','anchorages-icw-waccamaw-river-point','anchorages-georgetown-winyah-peedee-black-river','anchorages-icw-belle-isle-sullivans-island','anchorages-charleston-cooper-wando-ashley','anchorages-icw-stono-edisto','anchorages-icw-dawho-ashepoo-coosaw-cutoff','anchorages-icw-coosaw-ladys-island-bridge','anchorages-beaufort','anchorages-icw-beaufort-calibogue-hilton-head','anchorages-icw-cooper-savannah','sc-marinas','marinas-sc-icw-calabash-socastee-bridge','marinas-sc-icw-waccamaw-river-point','marinas-sc-georgetown-winywah-peedee-black-river','marinas-sc-belle-sullivans','marinas-sc-charleston-cooper-wando-ashley','marinas-sc-icw-stono-edisto','marinas-sc-icw-dawho-ashepoo-coosaw','marinas-sc-icw-coosaw-ladys-island','marinas-sc-beaufort','marinas-sc-icw-beaufort-calibogue-hilton-head','marinas-sc-icw-cooper-river-savannah-river','sc-fuel-prices','bridges-south-carolina','sc-belle-isle-sullivans-ilsand','sc-chart-view-alerts','5-ashepoo-coosaw-cutoff-into-coosaw-river','intersection-of-wright-river-and-northern-fields-cut','sc-aicw-problems','ln™-sc-news','south-carolina-marinas-alphabetical-index','south-carolina-lpg-cng-availability'))) { ?>
<?php echo adrotate_banner(7,0,8,8); ?>
<?php echo adrotate_banner(8,0,8,8); ?>
<?php } elseif (is_page('georgia-fuel-prices') || in_category(array('georgia','ga-news-georgia','ga-news-savannah-river-to-savannah','ga-news-savannah-icw-crossing-hell-gate','ga-news-ogechee-st-simons-sound','ga-news-jekyll-creek-st-marys-river','anchorages-georgia','anchorages-savannah-river-to-savannah','anchorages-icw-elba-island-hell-gate','anchorages-icw-ogechee-st-simons','anchorages-icw-jekyll-creek-st-marys','marinas-georgia','marinas-ga-savannah-river-to-savannah','marinas-ga-icw-elba-island-hell-gate','marinas-ga-icw-ogechee-st-simons','marinas-ga-jekyll-creek','ga-fuel-prices','bridges-ga-bridges','ga-chart-view-alerts','6-fields-cut','7-hell-gate','8-little-mud-river','9-jekyll-creek','ga-aicw-problems','ln™-ga-news','georgia-marinas-alphabetical-index','ga-lpg-cng-availability'))) { ?>
<?php echo adrotate_banner(9,0,8,8); ?>
<?php echo adrotate_banner(10,0,8,8); ?>
<?php } elseif (is_page(array('eastern-florida-fuel-prices','st-johns-fuel-prices')) || in_category(array('eastern-florida','east-fl-eastern-florida','east-fl-st-marys-sisters-creek','east-fl-st-johns-jacksonville-palatka-sanford','east-fl-jacksonville-vilano','east-fl-st-augustine','east-fl-san-sebastian-daytona','east-fl-port-orange-haulover-canal','east-fl-northern-indian-river-titusville-melborne','east-fl-melbourne-beach-st-lucie-stuart','east-fl-great-pocket-palm-beach','east-fl-lantana-las-olas-boulevard','east-fl-fort-lauderdale','east-fl-everglades-miami-government','anchorages-eastern-florida','east-fl-st-johns-anchorages','anchorages-icw-st-marys-sisters-creek','anchorages-st-johns-river-mayport-jacksonville','anchorages-st-johns-ortega-palatka','anchorages-st-johns-river-devils-elbow-lake-george','anchorages-st-johns-river-astor-monroe','anchorages-icw-jacksonville-vilano-beach','anchorages-st-augustine','anchorage-icw-san-sebastian-daytona','anchorages-icw-port-orange-haulover-canal','anchorages-icw-northern-indian-titusville-melbourne','anchorages-icw-melbourne-beach-st-lucie-stuart','anchorages-icw-great-pocket-palm-beach','east-fl-lantana-las-olas-boulevard','anchorages-fort-lauderdale','anchorages-icw-everglades-miami-government','east-fl-marinas','marina-east-fl-st-marys-river-sisters-creek','east-fl-st-johns-river-marinas','marina-east-fl-jacksonville-beach-vilano-bridge','marina-east-fl-st-augustine','marina-east-fl-san-sebastian-daytona','marina-east-fl-port-orange-haulover','marina-east-fl-northern-indian-river-titusville-melbourne','marina-east-fl-melbourne-st-lucie-stuart','marina-east-fl-great-pocket-palm-beach','marina-east-fl-lantana-las-olas-boulevard','marina-east-fl-fort-lauderdale','marina-east-fl-everglades-miami-government','east-fl-fuel-prices','bridges-eastern-florida','east-fl-northern-indian-river-titusville-melbourne','east-fl-everglades-miami-government','st-johns-fuel-prices','ef-chart-view-alerts','intersection-of-aicw-and-mantanzas-inlet','ef-aicw-problems','ln™-ef-news','eastern-florida-st-johns-river-marinas-alphabetical-index','e-florida-lpg-cng-availability'))) { ?>
<?php echo adrotate_banner(11,0,8,8); ?>
<?php echo adrotate_banner(12,0,8,8); ?>
<?php } elseif (is_page('keys-fuel-prices') || in_category(array('florida-keys','keys-florida-keys','keys-inside-passage-dinner-key-jewfish','keys-inside-route-blackwater-tavernier','keys-florida-bay-cross-bank-channel-five','keys-florida-bay-old-dan-bank-moser','keys-hawk-channel-long-key-moser','keys-marathon-boot-key-harbor','marina-keys-routes-marathon-channel-five-sable','keys-back-route-marathon-key-west','keys-hawk-channel-sombrero-key-west-1','keys-key-west','keys-routes-dry-tortugas','all-florida-keys-anchorages','anchorages-dinner-key-coconut-grove-jewfish','anchorages-blackwater-tavernier','anchorages-hawk-channel-govt-inlet-tavernier','anchorages-cross-bank-channel-five','anchorages-hawk-channel-tavernier-key-channel-five','anchorages-old-dan-bank-moser-channel','anchorages-hawk-channel-long-key-moser-channel','anchorages-marathon-boot-key-harbor','anchorages-marathon-key-west','anchorages-hawk-channel-sombrero-key-west','key-west-anchorages','keys-marinas','marina-keys-florida-bay-blackwater-tavernier','marina-keys-hawk-government-tavernier','marina-keys-florida-bay-cross-bank-channel-five','marina-keys-hawk-tavernier-channel-five','marina-keys-florida-bay-old-dan-bank-moser','marina-keys-hawk-channel-long-key-moser','marina-keys-marathon-boot-key','marina-keys-back-route-marathon-key-west','marina-keys-hawk-sombrero-key-west','marina-keys-key-west','keys-fuel-prices','bridges-florida-keys','keys-hawk-channel-government-tavernier','keys-hawk-channel-tavernier-key-channel-five','flk-chart-view-alerts','ln™-flk-news','florida-keys-marinas-alphabetical-index','fl-keys-lpgcng-availability'))) { ?>
<?php echo adrotate_banner(13,0,8,8); ?>
<?php echo adrotate_banner(14,0,8,8); ?>
<?php } elseif (is_page('western-florida-fuel-prices') || in_category(array('western-florida','west-fl-western-florida','west-fl-cape-sable-pavillion-key','west-fl-10000-indian-key-pass','west-fl-marco-island-naples','west-fl-gordon-fort-myers','west-fl-caloosahatchee-fort-myers','west-fl-icw-miserable-mile-gasparilla','west-fl-charlotte-harbor-punta-gorda','west-fl-icw-placida-venice','west-fl-icw-venice-tampa','west-fl-tampa-bay','west-fl-icw-boca-ciega-clearwater','west-fl-icw-dunedin-anclote-river','west-fl-big-bend-anclote-dog-carr','anchorages-western-florida','wf-anchorages-cape-sable-pavillion-key','wf-anchorages-10000-indian-everglades','wf-anchorages-marco-island-naples','wf-anchorages-gordon-pass-fort-myers-beach','wf-anchorages-caloohatchee-river-fort-myers','wf-anchorages-miserable-mile-gasparilla','wf-anchorages-charlotte-harbor-punta-gorda-peace','wf-anchorages-placida-venice','wf-anchorages-venice-anna-maria','wf-anchorages-tampa-bay','wf-anchorages-boca-ciega-clearwater','wf-anchorages-dunedin-anclote-tarpon','wf-anchorages-anclote-dog-carrabelle','west-fl-marinas','marina-west-fl-cape-sable-pavillion-key','marina-west-fl-10000-indian-key-pass','marina-west-fl-marco-island-nables','marina-west-fl-gordon-pass-fort-myers','marina-west-fl-caloosahatchee-fort-myers','marina-west-fl-icw-miserable-mile-gasparilla','marina-west-fl-charlotte-harbor-punta-gorda','marina-west-fl-icw-venice-tampa','marina-west-fl-tampa-bay','marina-west-fl-icw-boca-ciega-clearwater','marina-west-fl-icw-dunedin-ancolite','marina-west-fl-big-bend-region-ancolite-dog-carr','west-fl-fuel-prices','bridges-western-florida','wf-chart-view-alerts','ln™-wf-news','western-florida-marinas-alphabetical-index','wf-lpgcng-availability'))) { ?>
<?php echo adrotate_banner(15,0,8,8); ?>
<?php echo adrotate_banner(16,0,8,8); ?>
<?php } elseif (in_category(array('okeechobee','content-okeechobee'))) { ?>
<?php echo adrotate_banner(17,0,8,8); ?>
<?php echo adrotate_banner(18,0,8,8); ?>
<?php } elseif (in_category(array('northern-gulf','ngulf-northern-gulf','ngulf-carrabelle-apalachicola','ngulf-apalachicola-east','ngulf-panama-city-inlet-st-andrews','ngulf-hathaway-bridge-pensacol','ngulf-pensacola-inlet','ngulf-big-lagoon-mobile-bay','ngulf-mobile-bay-mobile','ngulf-pas-aux-herons-rigolets','ngulf-lake-pontchartrain-new-orleans','ngulf-mississippi-river-grand','bridges-northern-gulf'))) { ?>
<?php echo adrotate_banner(19,0,8,8); ?>
<?php echo adrotate_banner(20,0,8,8); ?>
<?php } elseif (in_category(array('bahamas','bahamas-sub','bahamas-archives'))) { ?>
<?php echo adrotate_banner(21,0,8,8); ?>
<?php echo adrotate_banner(22,0,8,8); ?>
<?php } elseif (in_category(array('chartview','maps','florida-keys-maps','georgia-maps','north-carolina-maps','northeast-florida-maps','sourth-florida-maps','south-carolina-maps','southeast-florida-maps','southwest-florida-maps','north-carolina-maps','northeast-florida-maps','southeast-florida-maps','southwest-florida-maps'))) { ?>
<?php echo adrotate_banner(27,0,8,8); ?>
<?php echo adrotate_banner(28,0,8,8); ?>
<?php } elseif (in_category(array('weather','photo-of-the-week','weather-sub', 'coastal-tides', 'local-forecasts', 'local-forecasts-rss', 'tidal-information'))) { ?>
<?php echo adrotate_banner(23,0,8,8); ?>
<?php echo adrotate_banner(24,0,8,8); ?>
<?php } else { ?>
<?php echo adrotate_banner(1,0,8,8); ?>
<?php echo adrotate_banner(2,0,8,8); ?>
<?php } ?>